-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 22:57:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maintenance_system_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maintenance_system_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maintenance_system_db` DEFAULT CHARACTER SET utf8 ;
USE `maintenance_system_db` ;

-- -----------------------------------------------------
-- Table `maintenance_system_db`.`maintenance_object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`maintenance_object` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `object_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`object_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`object_contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `telephone` INT(12) NULL,
  `address` VARCHAR(45) NOT NULL,
  `object_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_idx` (`object_id` ASC) VISIBLE,
  CONSTRAINT `fk_object_c_id`
    FOREIGN KEY (`object_id`)
    REFERENCES `maintenance_system_db`.`maintenance_object` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`technical_system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`technical_system` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `object_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_maint_object_idx` (`object_id` ASC) VISIBLE,
  CONSTRAINT `fk_maint_object`
    FOREIGN KEY (`object_id`)
    REFERENCES `maintenance_system_db`.`maintenance_object` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`user_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`employee_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`employee_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  `technical_system_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tech_syst_id_idx` (`technical_system_id` ASC) VISIBLE,
  CONSTRAINT `fk_tech_syst_id`
    FOREIGN KEY (`technical_system_id`)
    REFERENCES `maintenance_system_db`.`technical_system` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`user_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(30) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `user_role_id` INT NOT NULL,
  `employee_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_id_idx` (`user_role_id` ASC) VISIBLE,
  INDEX `fk_employee_type_id_idx` (`employee_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role_id`
    FOREIGN KEY (`user_role_id`)
    REFERENCES `maintenance_system_db`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_type_id`
    FOREIGN KEY (`employee_type_id`)
    REFERENCES `maintenance_system_db`.`employee_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`maintenance_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`maintenance_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creator_id` INT NOT NULL,
  `object_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_creator_id_idx` (`creator_id` ASC) VISIBLE,
  INDEX `fk_object_plan_id_idx` (`object_id` ASC) VISIBLE,
  CONSTRAINT `fk_creator_id`
    FOREIGN KEY (`creator_id`)
    REFERENCES `maintenance_system_db`.`user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_object_plan_id`
    FOREIGN KEY (`object_id`)
    REFERENCES `maintenance_system_db`.`maintenance_object` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`maintenance_plan_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`maintenance_plan_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `maintenance_plan_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_maintanence_plan_id_idx` (`maintenance_plan_id` ASC) VISIBLE,
  CONSTRAINT `fk_maintanence_plan_id`
    FOREIGN KEY (`maintenance_plan_id`)
    REFERENCES `maintenance_system_db`.`maintenance_plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`system_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`system_device` (
  `id` INT NOT NULL,
  `system_id` INT NOT NULL,
  `device_id` INT NOT NULL,
  `maintenance_plan_item_id` INT NULL,
  INDEX `fk_device_id_idx` (`device_id` ASC) VISIBLE,
  INDEX `fk_m_p_i_id_idx` (`maintenance_plan_item_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_system_id`
    FOREIGN KEY (`system_id`)
    REFERENCES `maintenance_system_db`.`technical_system` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_s_device_id`
    FOREIGN KEY (`device_id`)
    REFERENCES `maintenance_system_db`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_m_p_i_id`
    FOREIGN KEY (`maintenance_plan_item_id`)
    REFERENCES `maintenance_system_db`.`maintenance_plan_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`user_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`user_contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `telephone` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `user_account_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_account_id_idx` (`user_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_account_id`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `maintenance_system_db`.`user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`work_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`work_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `workload` INT NOT NULL,
  `work_name` VARCHAR(45) NOT NULL,
  `syst_device_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_device_workload_id_idx` (`syst_device_id` ASC) VISIBLE,
  CONSTRAINT `fk_device_workload_id`
    FOREIGN KEY (`syst_device_id`)
    REFERENCES `maintenance_system_db`.`system_device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maintenance_system_db`.`work_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maintenance_system_db`.`work_result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `comment` VARCHAR(450) NULL,
  `employee_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_t_id_idx` (`employee_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_t_id`
    FOREIGN KEY (`employee_type_id`)
    REFERENCES `maintenance_system_db`.`employee_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
